### ISSUE TITLE
[Feature request] Add an UI for listing and/or managing dispatchable prefixes

### ISSUE THREAD

**Issue by rail01** [Markus-Rost/InterwikiDispatcher#2]
Possible usability enhancement: consider adding a separate special page or hooking into Special:Interwiki to display list of dispatchable IW prefixes.

Another potential QoL feature would be an ability to add, modify and remove dispatchable prefixes from the UI with a proper log. Perhaps that could be hooked into S:Interwiki, too.

Either way, adding it as an issue for you to not forget and consider if you guys want to enhance this extension at any point.

**Comment by alex4401** [comment]
Throwing my cents:
- Management will require a full rewrite to move the configuration into a global database. This will require some curious hoops around the newly added `wikiExistsCallback`. I'd also say having the config manageable via PHP is rather useful, but those rules should not be editable via DB/web UI.
- Extension:Interwiki doesn't expose any hooks to modify the special page's output. There.... "could" be a way via generic page hooks, but it's unsavoury and discards a lot of built-in MW features.
- Viewing is good. ... No idea how useful (personally), but it's easy to implement. This'd need to be a new special page.

**Comment by Markus-Rost** [comment]
An extra table listing dispatchable IW prefixes has been added to the bottom of Special:Interwiki.
